insert into USUARIO (ID_USUARIO, PASSWORD, NOMBRE_USUARIO, ACTIVO ) values ('admin', 'admin', 'Administrador', 1)

insert into PRODUCTO (ID_PRODUCTO,NOMBRE_PRODUCTO, CANTIDAD_DISPONIBLE, ACTIVO, FECHA_CREACION, USUARIO_CREACION) values (SEQ_PRODUCTO.nextVal,'Gorra Spiderman', 15, 1, '2018-08-11', 'admin')

insert into PRODUCTO (ID_PRODUCTO,NOMBRE_PRODUCTO, CANTIDAD_DISPONIBLE, ACTIVO, FECHA_CREACION, USUARIO_CREACION) values (SEQ_PRODUCTO.nextVal,'Action Comics #1', 10, 1, '2018-08-11', 'admin')

insert into PRODUCTO (ID_PRODUCTO,NOMBRE_PRODUCTO, CANTIDAD_DISPONIBLE, ACTIVO, FECHA_CREACION, USUARIO_CREACION) values (SEQ_PRODUCTO.nextVal,'Spiderman #74', 5, 1, '2018-08-11', 'admin')

insert into PRODUCTO (ID_PRODUCTO,NOMBRE_PRODUCTO, CANTIDAD_DISPONIBLE, ACTIVO, FECHA_CREACION, USUARIO_CREACION) values (SEQ_PRODUCTO.nextVal,'Kaliman La Pelicula DVD', 3, 1, '2018-08-11', 'admin')


insert into MOVIMIENTO_PRODUCTO (ID_MOVIMIENTO, ID_PRODUCTO, CONCEPTO, FECHA, CANTIDAD, SALDO, ID_USUARIO) values (SEQ_MOVIMIENTO.nextVal, 1, 'Inventario Inicial', '2018-08-11', 15, 15, 'admin')

insert into MOVIMIENTO_PRODUCTO (ID_MOVIMIENTO, ID_PRODUCTO, CONCEPTO, FECHA, CANTIDAD, SALDO, ID_USUARIO) values (SEQ_MOVIMIENTO.nextVal, 51, 'Inventario Inicial', '2018-08-11', 10, 10, 'admin')

insert into MOVIMIENTO_PRODUCTO (ID_MOVIMIENTO, ID_PRODUCTO, CONCEPTO, FECHA, CANTIDAD, SALDO, ID_USUARIO) values (SEQ_MOVIMIENTO.nextVal, 101, 'Inventario Inicial', '2018-08-11', 5, 5, 'admin')

insert into MOVIMIENTO_PRODUCTO (ID_MOVIMIENTO, ID_PRODUCTO, CONCEPTO, FECHA, CANTIDAD, SALDO, ID_USUARIO) values (SEQ_MOVIMIENTO.nextVal, 151, 'Inventario Inicial', '2018-08-11', 3, 3, 'admin')