
-- metamodelo
CREATE TABLE XMMTMDL (
  ID_METAMODELO INTEGER PRIMARY KEY AUTOINCREMENT,
  NOMBRE_METAMODELO VARCHAR(16) NOT NULL,
  ID_TIPO_RAIZ INTEGER
);
-- tipo de dato en metamodelo
CREATE TABLE XMTPMTMDL (
  ID_METAMODELO INTEGER NOT NULL,
  ID_TIPO_METAMODELO VARCHAR (32) NOT NULL,
  NOMBRE_TIPO_METAMODELO VARCHAR(32) NOT NULL,
  PRIMARY KEY (ID_METAMODELO, ID_TIPO_METAMODELO )
--  FOREIGN KEY XM_FK_TP_MTMDL (ID_METAMODELO) REFERENCES XMMTMDL (ID_METAMODELO)
);
-- tipos primitivos
CREATE TABLE XMTPPRMTV (
  ID_TIPO_PRIMITIVO VARCHAR(12) NOT NULL,
  REQUIERE_LONGITUD CHAR (1) NOT NULL,
  REQUIERE_PRECISION CHAR (1) NOT NULL,
  SOPORTA_EXPRESION_REGULAR CHAR (1) NOT NULL,
  EXP_REGULAR_DEFAULT VARCHAR(32),
  PRIMARY KEY ( ID_TIPO_PRIMITIVO )
);
--atributo de tipo en metamodelo
CREATE TABLE XMATRBTMTMDL (
  ID_METAMODELO INTEGER NOT NULL,
  ID_TIPO_METAMODELO VARCHAR (32) NOT NULL,
  ID_ATRIBUTO_METAMODELO VARCHAR (32) NOT NULL,
  ID_TIPO_PRIMITIVO VARCHAR (12),
  ID_TIPO_METAMODELO_REF VARCHAR (32),
  ES_OBLIGATORIO CHAR(1),
  LONGITUD_ATRIBUTO INTEGER,
  PRECISION_ATRIBUTO INTEGER,
  ORDEN INTEGER NOT NULL,
  EXP_REGULAR_VALIDACION VARCHAR(32),
  PRIMARY KEY (ID_METAMODELO, ID_TIPO_METAMODELO, ID_ATRIBUTO_METAMODELO )
--  ,FOREIGN KEY XM_FK_ATR_TPMTMDL (ID_METAMODELO, ID_TIPO_METAMODELO ) REFERENCES XMTPMTMDL,
--  FOREIGN KEY XM_FK_ATR_TPPRMTV ID_TIPO_PRIMITIVO ) REFERENCES XMTPPRMTV
);
-- jerarquia de tipos
CREATE TABLE XMJRRQTP (
  ID_METAMODELO INTEGER NOT NULL,
  ID_TIPO_METAMODELO_PADRE VARCHAR (32) NOT NULL,
  ID_JERARQUIA VARCHAR (32) NOT NULL,
  ID_TIPO_METAMODELO_HIJO VARCHAR (32) NOT NULL,
  ES_MULTIPLE CHAR(1) NOT NULL,
  PRIMARY KEY (ID_METAMODELO, ID_TIPO_METAMODELO_PADRE, ID_JERARQUIA )
);
-- modelo que aplica metamodelos
CREATE TABLE XMMDL (
  ID_MODELO INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_METAMODELO INTEGER NOT NULL,
  ID_OBJETO_RAIZ INTEGER
);
-- objeto perteneciente a un modelo
CREATE TABLE XMOBJTMDL (
  ID_OBJETO INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_MODELO INTEGER NOT NULL,
  ID_METAMODELO INTEGER NOT NULL,
  ID_TIPO_METAMODELO VARCHAR (32) NOT NULL,
  NOMBRE VARCHAR(32) NOT NULL,
  DESCRIPCION VARCHAR(256),
  ID_OBJETO_PADRE INTEGER,
  ORDEN INTEGER NOT NULL
);
-- atributos de un objeto modelado
CREATE TABLE XMATRBTOBJT (
  ID_OBJETO INTEGER NOT NULL,
  ID_ATRIBUTO_METAMODELO VARCHAR (32) NOT NULL,
  VALOR VARCHAR (32),
  PRIMARY KEY ( ID_OBJETO, ID_ATRIBUTO_METAMODELO )
);