DELETE FROM XMATRBTMTMDL WHERE ID_METAMODELO = 2 AND ID_TIPO_METAMODELO = 'METAMODELO' AND ID_ATRIBUTO_METAMODELO = 'nombre';
DELETE FROM XMATRBTMTMDL WHERE ID_METAMODELO = 2 AND ID_TIPO_METAMODELO = 'TIPO_METAMODELO' AND ID_ATRIBUTO_METAMODELO = 'idTipoMetamodelo';
DELETE FROM XMATRBTMTMDL WHERE ID_METAMODELO = 2 AND ID_TIPO_METAMODELO = 'ATRIBUTO_METAMODELO' AND ID_ATRIBUTO_METAMODELO = 'idAtributo';
DELETE FROM XMATRBTMTMDL WHERE ID_METAMODELO = 2 AND ID_TIPO_METAMODELO = 'JERARQUIA' AND ID_ATRIBUTO_METAMODELO = 'idJerarquia';

--DELETE FROM XMATRBTOBJT WHERE ID_ATRIBUTO_METAMODELO = 'nombre' AND EXISTS ( SELECT 1 FROM XMOBJTMDL as b , XMMDL as c WHERE b.ID_MODELO = c.ID_MODELO AND b.ID_OBJETO =a.ID_OBJETO AND b.ID_TIPO_METAMODELO = 'METAMODELO' AND c.ID_METAMODELO = 2 );
--DELETE FROM XMATRBTOBJT as a WHERE a.ID_ATRIBUTO_METAMODELO = 'idTipoMetamodelo' AND EXISTS ( SELECT 1 FROM XMOBJTMDL as b , XMMDL as c WHERE b.ID_MODELO = c.ID_MODELO AND b.ID_OBJETO =a.ID_OBJETO AND b.ID_TIPO_METAMODELO = 'TIPO_METAMODELO' AND c.ID_METAMODELO = 2 );
--DELETE FROM XMATRBTOBJT as a WHERE a.ID_ATRIBUTO_METAMODELO = 'idAtributo' AND EXISTS ( SELECT 1 FROM XMOBJTMDL as b , XMMDL as c WHERE b.ID_MODELO = c.ID_MODELO AND b.ID_OBJETO =a.ID_OBJETO AND b.ID_TIPO_METAMODELO = 'ATRIBUTO_METAMODELO' AND c.ID_METAMODELO = 2 );
--DELETE FROM XMATRBTOBJT as a WHERE a.ID_ATRIBUTO_METAMODELO = 'idJerarquia' AND EXISTS ( SELECT 1 FROM XMOBJTMDL as b , XMMDL c WHERE b.ID_MODELO = c.ID_MODELO AND b.ID_OBJETO =a.ID_OBJETO AND b.ID_TIPO_METAMODELO = 'JERARQUIA' AND c.ID_METAMODELO = 2 );

DELETE FROM XMATRBTOBJT WHERE ID_ATRIBUTO_METAMODELO = 'nombre' AND ID_OBJETO in ( SELECT b.ID_OBJETO FROM XMOBJTMDL b , XMMDL c WHERE b.ID_MODELO = c.ID_MODELO AND b.ID_TIPO_METAMODELO = 'METAMODELO' AND c.ID_METAMODELO = 2 );
DELETE FROM XMATRBTOBJT WHERE ID_ATRIBUTO_METAMODELO = 'idTipoMetamodelo' AND ID_OBJETO in ( SELECT b.ID_OBJETO FROM XMOBJTMDL b , XMMDL c WHERE b.ID_MODELO = c.ID_MODELO AND b.ID_TIPO_METAMODELO = 'TIPO_METAMODELO' AND c.ID_METAMODELO = 2 );
DELETE FROM XMATRBTOBJT WHERE ID_ATRIBUTO_METAMODELO = 'idAtributo' AND ID_OBJETO in ( SELECT b.ID_OBJETO FROM XMOBJTMDL b , XMMDL c WHERE b.ID_MODELO = c.ID_MODELO AND b.ID_TIPO_METAMODELO = 'ATRIBUTO_METAMODELO' AND c.ID_METAMODELO = 2 );
DELETE FROM XMATRBTOBJT WHERE ID_ATRIBUTO_METAMODELO = 'idJerarquia' AND ID_OBJETO in ( SELECT b.ID_OBJETO FROM XMOBJTMDL b , XMMDL c WHERE b.ID_MODELO = c.ID_MODELO AND b.ID_TIPO_METAMODELO = 'JERARQUIA' AND c.ID_METAMODELO = 2 );

INSERT INTO XMJRRQTP( ID_METAMODELO,ID_TIPO_METAMODELO_PADRE,ID_JERARQUIA,ID_TIPO_METAMODELO_HIJO,ES_MULTIPLE )VALUES( 2,'METAMODELO'     ,'Generadores'       ,'GENERADOR'    ,'1');
