--tipos primitivos
UPDATE XMTPPRMTV SET SOPORTA_EXPRESION_REGULAR = '1' ,EXP_REGULAR_DEFAULT = '^\d{1,5}$' WHERE ID_TIPO_PRIMITIVO = 'INTEGER' ;
UPDATE XMTPPRMTV SET SOPORTA_EXPRESION_REGULAR = '1' ,EXP_REGULAR_DEFAULT = '^\d{1,10}$' WHERE ID_TIPO_PRIMITIVO = 'LONG' ;
UPDATE XMTPPRMTV SET SOPORTA_EXPRESION_REGULAR = '1' ,EXP_REGULAR_DEFAULT = '^\d+(\.\d{1,10})?$' WHERE ID_TIPO_PRIMITIVO = 'DECIMAL' ;
UPDATE XMTPPRMTV SET SOPORTA_EXPRESION_REGULAR = '1' ,EXP_REGULAR_DEFAULT = '^\d+(\.\d{1,5})?$' WHERE ID_TIPO_PRIMITIVO = 'FLOAT' ;
UPDATE XMTPPRMTV SET SOPORTA_EXPRESION_REGULAR = '1' ,EXP_REGULAR_DEFAULT = '^\d+(\.\d{1,10})?$' WHERE ID_TIPO_PRIMITIVO = 'DOUBLE' ;
UPDATE XMTPPRMTV SET SOPORTA_EXPRESION_REGULAR = '1' ,EXP_REGULAR_DEFAULT = '^[0123]\d\/[01]\d\/\d{4}$' WHERE ID_TIPO_PRIMITIVO = 'DATE' ;
UPDATE XMTPPRMTV SET SOPORTA_EXPRESION_REGULAR = '1' ,EXP_REGULAR_DEFAULT = '^[01]$' WHERE ID_TIPO_PRIMITIVO = 'BOOLEAN' ;

--metamodelos

UPDATE XMATRBTMTMDL SET EXP_REGULAR_VALIDACION = '^[A-Z][A-Z0-9_]{0,29}$' WHERE ID_METAMODELO = 1 AND ID_TIPO_METAMODELO = 'ENTIDAD' AND ID_ATRIBUTO_METAMODELO = 'nombreTabla';
UPDATE XMATRBTMTMDL SET EXP_REGULAR_VALIDACION = '^[A-Z][A-Z0-9_]{0,29}$' WHERE ID_METAMODELO = 1 AND ID_TIPO_METAMODELO = 'CAMPO' AND ID_ATRIBUTO_METAMODELO = 'nombreCampo';


